name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
 push:
  branches:
   - "**"
 pull_request:
  types: [opened, synchronize, edited, ready_for_review]
  branches:
   main

env:
## Set your API token as a GitHub secret
 ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - run: sudo apt update && sudo apt install curl -y sudo bash git
   - name: Checkout dev-update
     uses: actions/checkout@v4
##   - name: Create preview Deployment
##     uses: astronomer/deploy-action@v0.2
##     with:
##      action: create-deployment-preview
      ##deployment-id: clqngd12632891lqzzy2pd6iz1
##      deployment-name: Github-Actions-Test
      
   - name: Deploy code to preview
     uses: astronomer/deploy-action@v0.2
     with:
      action: deploy-deployment-preview
       # deployment-name: Branch-Development
      deployment-name: Github-Actions-Test # ${{ secrets.DEV_ASTRO_DEPLOYMENT_ID }}
      #workspace: cky3avnqa828981d1obi0dcb6v

