name: Deployment Request Process

on:
  push:
    branches:
     - main

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
jobs:
  deployment_creation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        shell: bash
        run: |
          sudo apt update \
          && sudo apt install curl unzip -y
   
      - name: Create deployment
        shell: bash
        run: |
          curl -sSLv https://install.astronomer.io | bash -s
          export PATH="$HOME/.astro/bin:$PATH"  # Add Astronomer CLI to PATH
          which astro
          astro version  # Verify installation
